---
title: "Trip Change Documentation"
format:
  html:
    embed-resources: true
theme: flatly
editor: visual
---

# South Link Trip Change Dashboard

## About

This dashboard shows the anticipated level of change in trip volumes for the South Link network as compared to service levels in Fall 2024. We chose Fall 2024 as the baseline comparison point because it includes the Lynnwood Link service restructure.

## Using the Dashboard

Use the filters to make selections to view the time of day, geography, metric and period you are interested in. When you have made selections, click "Load Map & Filters" on the left-hand side of the screen to render the map.

All boxes on the main screen can be re-sized. Hold and drag an edge to make the map or table bigger or smaller. If you need more screen real estate, all metric filters can be collapsed.

## Metrics

The dashboard has several metrics available for planners. All reference the same data and can be used together to develop an understanding of the scale and size of change in an area.

**Trips per Geo Baseline:** The number of trips in the baseline network passing through the hexagon on the day (weekday, Saturday, Sunday) and period as selected in the dashboard.

**Trips per Geo Proposed:** The number of trips in the proposednetwork passing through the hexagon on the day (weekday, Saturday, Sunday) and period as selected in the dashboard.

**Avg Trips/Hour (Baseline or Proposed):** The number of trips per hour passing through the hexagon on the day (weekday, Saturday, Sunday) and period as selected in the dashboard. For routes with spans of service that only cover a portion of a period, the dashboard assumes that the average should be calculated using the total number of hours in the period. In other words, if a route has its last trip at 7:10 PM, it will have records available in the "7 PM - 10 PM" period, but the average number of trips per hour will be less than 1.

**Change in Trips:** The change in number of trips passing through the hexagon on the day (weekday, Saturday, Sunday) and period as selected in the dashboard. Change is calculated based on the Fall 2021 network.

**Change in Avg Trips/Hour:** The change in number of trips per hour passing through the hexagon on the day (weekday, Saturday, Sunday) and period as selected in the dashboard. Change is calculated based on the Fall 2021 network.

**Percent Change in Trips:** The percent change in number of trips passing through the hexagon on the day (weekday, Saturday, Sunday) and period as selected in the dashboard. Change is calculated based on the Spring 2020 network.

**Percent Change in Avg Trips per Hour:** The percent change in number of trips per hour passing through the hexagon on the day (weekday, Saturday, Sunday) and period as selected in the dashboard. Change is calculated based on the Fall 2021 network.

**New Coverage Trips:** This metric identifies areas that will have service in the future network scenario that did not have service in 2021.

**Lost Coverage Trips:** This metric identifies areas that will lose all service in the future network scenario. Small changes in stop placement can affect this metric, especially if 1/8th mile hexagons are selected as the analysis geography.

**Total Capacity (Baseline or Proposed):** The number of passengers that can travel on trips passing through the selected geography during the period selected. This can be useful to look at when services are moving from a service with a smaller capacity to services with a larger capacity (e.g. bus to rail).

**Change in Capacity:** The change in the number of passengers that can be accommodated on planned service.

**New Coverage Capacity:** The anticipated passenger capacity of services traveling through areas gaining new service.

**Lost Coverage Capacity:** The passenger capacity of services traveling through areas losing service.

**Percent Change in Capacity:** The percent change in passenger capacity between the baseline and proposed networks. This can highlight areas where anticipated vehicle size will increase rider's transit opportunities even when trips are not increasing. Areas gaining/losing all coverage are not included in this calculation due to calculation limitations.

**Difference Between Pct Capacity Change and Trip Change:** The difference between the percent capacity change and the percent change in trips. The difference can highlight where trip conversion to light rail increases transit opportunities even if the number of trips is decreasing.

## More Info

This app was developed in R using shinydashboard by Melissa Gaughan. For code and technical documentation see <https://github.com/melissa-gaughan>.
